### ISSUE TITLE
No module named src.ircclient

### ISSUE THREAD

**Issue by haxxus** [Hackndo/discord-irc-sync#2] opened 2017-11-28 16:32 UTC
Traceback (most recent call last):
  File "discord-irc-sync.py", line 7, in <module>
    from src.ircclient import IRCClient
ImportError: No module named src.ircclient

**Comment by Hackndo** [comment] 2017-11-28 17:01
Hello,

Make sure you use **Python3.5+**

**Comment by haxxus** [comment] 2017-11-29 13:59
I have python 3.6

**Comment by Hackndo** [comment] 2017-11-29 15:29
Sorry, cannot reproduce
```
pixis@hackndo:~/Tools/slack-irc-sync $ mkvirtualenv python36 -p $(which python3.6)
Running virtualenv with interpreter /usr/bin/python3.6
Using base prefix '/usr'
[...]
(python36) pixis@hackndo:~/Tools/slack-irc-sync $ python -V
Python 3.6.3
(python36) pixis@hackndo:~/Tools/slack-irc-sync $ pip install -r requirements.txt
Collecting slackclient (from -r requirements.txt (line 1))
  Downloading slackclient-1.1.0.tar.gz
Collecting irc (from -r requirements.txt (line 2))
  Using cached irc-16.1-py2.py3-none-any.whl
[...]
(python36) pixis@hackndo:~/Tools/slack-irc-sync $ python slack-irc-sync.py 
[Slack] Logged in as:
[Slack] irc-sync
[IRC] Logged in as:
[IRC] slack
```

Please provide a more detailed issue (step by step to reproduce)

Thanks :)

**Comment by Hackndo** [comment] 2017-11-29 15:33
Sorry, cannot reproduce
```
pixis@hackndo:~/Tools/discord-irc-sync $ mkvirtualenv python36 -p $(which python3.6)
Running virtualenv with interpreter /usr/bin/python3.6
Using base prefix '/usr'
[...]
(python36) pixis@hackndo:~/Tools/discord-irc-sync $ python -V
Python 3.6.3
(python36) pixis@hackndo:~/Tools/discord-irc-sync $ pip install -r requirements.txt
Collecting discord (from -r requirements.txt (line 1))
  Using cached discord-0.0.2.tar.gz
Collecting irc (from -r requirements.txt (line 2))
  Using cached irc-16.1-py2.py3-none-any.whl

[...]
(python36) pixis@hackndo:~/Tools/discord-irc-sync$ python discord-irc-sync.py 
[IRC] Logged in as:
[IRC] discord-sync
[Discord] Logged in as:
[Discord] irc-sync
```

Please provide a more detailed issue (step by step to reproduce)

Thanks :)

**Comment by Hackndo** [comment] 2017-11-29 15:35
SSL import was missing, but that's not related. Fixed in [#c310e44](https://github.com/Hackndo/discord-irc-sync/commit/c310e443464894caa93ea33854a55184fdc91bb6)

**Comment by haxxus** [comment] 2017-11-29 17:12
`[root@vultr ~]# cd /discord-irc-sync
[root@vultr discord-irc-sync]# mkvirtualenv discordirc -p $(which python3.6)
Already using interpreter /usr/local/bin/python3.6
Using base prefix '/usr/local'
New python executable in /root/.virtualenvs/discordirc/bin/python3.6
Also creating executable in /root/.virtualenvs/discordirc/bin/python
Installing setuptools, pip, wheel...done.
/usr/bin/python: No module named virtualenvwrapper
[root@vultr discord-irc-sync]# pip3.6 install -r requirements.txt
Collecting discord (from -r requirements.txt (line 1))
Requirement already satisfied: irc in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: discord.py in /usr/local/lib/python3.6/site-packages (from discord->-r requirements.txt (line 1))
Requirement already satisfied: jaraco.itertools>=1.8 in /usr/local/lib/python3.6/site-packages (from irc->-r requirements.txt (line 2))
Requirement already satisfied: six in /usr/local/lib/python3.6/site-packages (from irc->-r requirements.txt (line 2))
Requirement already satisfied: jaraco.logging in /usr/local/lib/python3.6/site-packages (from irc->-r requirements.txt (line 2))
Requirement already satisfied: jaraco.functools>=1.5 in /usr/local/lib/python3.6/site-packages (from irc->-r requirements.txt (line 2))
Requirement already satisfied: pytz in /usr/local/lib/python3.6/site-packages (from irc->-r requirements.txt (line 2))
Requirement already satisfied: jaraco.collections in /usr/local/lib/python3.6/site-packages (from irc->-r requirements.txt (line 2))
Requirement already satisfied: jaraco.text in /usr/local/lib/python3.6/site-packages (from irc->-r requirements.txt (line 2))
Requirement already satisfied: jaraco.stream in /usr/local/lib/python3.6/site-packages (from irc->-r requirements.txt (line 2))
Requirement already satisfied: more-itertools in /usr/local/lib/python3.6/site-packages (from irc->-r requirements.txt (line 2))
Requirement already satisfied: tempora>=1.6 in /usr/local/lib/python3.6/site-packages (from irc->-r requirements.txt (line 2))
Requirement already satisfied: websockets<4.0,>=3.1 in /usr/local/lib/python3.6/site-packages (from discord.py->discord->-r requirements.txt (line 1))
Requirement already satisfied: aiohttp<1.1.0,>=1.0.0 in /usr/local/lib/python3.6/site-packages (from discord.py->discord->-r requirements.txt (line 1))
Requirement already satisfied: inflect in /usr/local/lib/python3.6/site-packages (from jaraco.itertools>=1.8->irc->-r requirements.txt (line 2))
Requirement already satisfied: jaraco.classes in /usr/local/lib/python3.6/site-packages (from jaraco.collections->irc->-r requirements.txt (line 2))
Requirement already satisfied: async-timeout in /usr/local/lib/python3.6/site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py->discord->-r requirements.txt (line 1))
Requirement already satisfied: multidict>=2.0 in /usr/local/lib/python3.6/site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py->discord->-r requirements.txt (line 1))
Requirement already satisfied: chardet in /usr/local/lib/python3.6/site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py->discord->-r requirements.txt (line 1))
Installing collected packages: discord
Successfully installed discord-0.0.2

[root@vultr discord-irc-sync]# python discord-irc-sync.py
Traceback (most recent call last):
  File "discord-irc-sync.py", line 7, in <module>
    from src.ircclient import IRCClient
ImportError: No module named src.ircclient
[root@vultr discord-irc-sync]#
`

**Comment by Hackndo** [comment] 2017-11-29 17:40
Well, can't reproduce, so it's not possible for me to fix.

You can still fork and create a pull request with a working fix on your side.

**Comment by haxxus** [comment] 2017-11-29 19:34
what os your using ?

**Comment by Hackndo** [comment] 2017-11-29 21:26
Works on Kali, Debian (7, 8, 9) & Ubuntu

**Comment by haxxus** [comment] 2017-11-29 22:31
Ok now I set up a fresh debian 9 , steps:

root@vultr:~# cd /discord-irc-sync/
root@vultr:/discord-irc-sync# mkvirtualenv discordirc -p $(which python3)
Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /root/.virtualenvs/discordirc/bin/python3
Also creating executable in /root/.virtualenvs/discordirc/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /root/.virtualenvs/discordirc/bin/predea                                                                                                                                                                                                                                             ctivate
virtualenvwrapper.user_scripts creating /root/.virtualenvs/discordirc/bin/postde                                                                                                                                                                                                                                             activate
virtualenvwrapper.user_scripts creating /root/.virtualenvs/discordirc/bin/preact                                                                                                                                                                                                                                             ivate
virtualenvwrapper.user_scripts creating /root/.virtualenvs/discordirc/bin/postac                                                                                                                                                                                                                                             tivate
virtualenvwrapper.user_scripts creating /root/.virtualenvs/discordirc/bin/get_en                                                                                                                                                                                                                                             v_details
(discordirc) root@vultr:/discord-irc-sync# pip install -r requirements.txt
Collecting discord (from -r requirements.txt (line 1))
  Downloading discord-0.0.2.tar.gz
Collecting irc (from -r requirements.txt (line 2))
  Downloading irc-16.1-py2.py3-none-any.whl (74kB)
    100% |################################| 81kB 7.4MB/s
Collecting discord.py (from discord->-r requirements.txt (line 1))
  Downloading discord.py-0.16.12.tar.gz (414kB)
    100% |################################| 419kB 3.1MB/s
Collecting more-itertools (from irc->-r requirements.txt (line 2))
  Downloading more_itertools-3.2.0-py3-none-any.whl
Collecting jaraco.stream (from irc->-r requirements.txt (line 2))
  Downloading jaraco.stream-1.1.2-py2.py3-none-any.whl
Collecting jaraco.text (from irc->-r requirements.txt (line 2))
  Downloading jaraco.text-1.9.2-py2.py3-none-any.whl
Collecting jaraco.itertools>=1.8 (from irc->-r requirements.txt (line 2))
  Downloading jaraco.itertools-2.1-py2.py3-none-any.whl
Collecting jaraco.logging (from irc->-r requirements.txt (line 2))
  Downloading jaraco.logging-1.5-py2.py3-none-any.whl
Collecting six (from irc->-r requirements.txt (line 2))
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting pytz (from irc->-r requirements.txt (line 2))
  Downloading pytz-2017.3-py2.py3-none-any.whl (511kB)
    100% |################################| 512kB 2.8MB/s
Collecting tempora>=1.6 (from irc->-r requirements.txt (line 2))
  Downloading tempora-1.9-py2.py3-none-any.whl
Collecting jaraco.functools>=1.5 (from irc->-r requirements.txt (line 2))
  Downloading jaraco.functools-1.16-py2.py3-none-any.whl
Collecting jaraco.collections (from irc->-r requirements.txt (line 2))
  Downloading jaraco.collections-1.5.2-py2.py3-none-any.whl
Collecting aiohttp<1.1.0,>=1.0.0 (from discord.py->discord->-r requirements.txt (line 1))
  Downloading aiohttp-1.0.5-cp35-cp35m-manylinux1_x86_64.whl (150kB)
    100% |################################| 153kB 7.3MB/s
Collecting websockets<4.0,>=3.1 (from discord.py->discord->-r requirements.txt (line 1))
  Downloading websockets-3.4-cp35-cp35m-manylinux1_x86_64.whl (54kB)
    100% |################################| 61kB 10.4MB/s
Collecting inflect (from jaraco.itertools>=1.8->irc->-r requirements.txt (line 2))
  Downloading inflect-0.2.5-py2.py3-none-any.whl (58kB)
    100% |################################| 61kB 10.1MB/s
Collecting jaraco.classes (from jaraco.collections->irc->-r requirements.txt (line 2))
  Downloading jaraco.classes-1.4.3-py2.py3-none-any.whl
Collecting async-timeout (from aiohttp<1.1.0,>=1.0.0->discord.py->discord->-r requirements.txt (line 1))
  Downloading async_timeout-2.0.0-py3-none-any.whl
Collecting multidict>=2.0 (from aiohttp<1.1.0,>=1.0.0->discord.py->discord->-r requirements.txt (line 1))
  Downloading multidict-3.3.2-cp35-cp35m-manylinux1_x86_64.whl (441kB)
    100% |################################| 450kB 2.8MB/s
Collecting chardet (from aiohttp<1.1.0,>=1.0.0->discord.py->discord->-r requirements.txt (line 1))
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |################################| 143kB 8.7MB/s
Building wheels for collected packages: discord, discord.py
  Running setup.py bdist_wheel for discord ... done
  Stored in directory: /root/.cache/pip/wheels/34/99/85/1cf707486a24280bac9fad32ec0cc8ec1c8005b2efabb4eda5
  Running setup.py bdist_wheel for discord.py ... done
  Stored in directory: /root/.cache/pip/wheels/64/75/26/d222074ecf19644df920bd43ad578156fcb00e515efd1cd164
Successfully built discord discord.py
Installing collected packages: async-timeout, multidict, chardet, aiohttp, websockets, discord.py, discord, six,                                                                                                                                                                                                              more-itertools, jaraco.stream, jaraco.functools, jaraco.classes, jaraco.collections, jaraco.text, inflect, jara                                                                                                                                                                                                             co.itertools, pytz, tempora, jaraco.logging, irc
Successfully installed aiohttp-1.0.5 async-timeout-2.0.0 chardet-3.0.4 discord-0.0.2 discord.py-0.16.12 inflect-                                                                                                                                                                                                             0.2.5 irc-16.1 jaraco.classes-1.4.3 jaraco.collections-1.5.2 jaraco.functools-1.16 jaraco.itertools-2.1 jaraco.l                                                                                                                                                                                                             ogging-1.5 jaraco.stream-1.1.2 jaraco.text-1.9.2 more-itertools-3.2.0 multidict-3.3.2 pytz-2017.3 six-1.11.0 tem                                                                                                                                                                                                             pora-1.9 websockets-3.4
(discordirc) root@vultr:/discord-irc-sync# python discord-irc-sync.py
Traceback (most recent call last):
  File "discord-irc-sync.py", line 19, in <module>
    settings = json.loads(f.read())
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 28 column 1 (char 787)

**Comment by Hackndo** [comment] 2017-11-29 22:40
What is the content of your config.json file ?

**Comment by haxxus** [comment] 2017-11-29 22:48
{
    "irc": {
        "server": "irc.quakenet.org",
        "port": "6667",
        "ssl": false,
        "channel": "#sohva",
        "nickname": "discirc",
        "owner": "wasp_sk",
        "cmd_prefix": "\*",
        "output_msg": "<:username:> :message:",
        "output_cmd": "CMD by :username:",
        "log_events": true
    },
    "discord": {
        "server": "319817668117135362",
        "channel": "381596872390737923",
        "token": "xxx",
        "owner": "wasp.sk",
        "cmd_prefix": "\*",
        "output_msg": "<:username:> :message:",
        "output_cmd": "CMD by :username:",
        "log_events": true
    },
    "formatting": {
        "irc_to_discord": true,
        "discord_to_irc": true
    },
}

**Comment by Hackndo** [comment] 2017-11-29 23:02
Ok, found the issue. There's a comma that shouldn't be there in config.json.dist. Just fixed the issue with commit [#a614014](https://github.com/Hackndo/discord-irc-sync/commit/a614014ee81704377ec9acbb70630fc5ed6383b0)

Remove the comma here

```json
        "discord_to_irc": true
    },
}
```

So it becomes


```json
        "discord_to_irc": true
    }
}
```

PS : I removed your discord bot token from your comment... ;)

**Comment by haxxus** [comment] 2017-11-29 23:12
Yes! finally , ive been up 3 days trying to get one working , out of all the irc-disc bots out there on GitHub this is been the first to work ! , thanks .

**Comment by Hackndo** [comment] 2017-11-29 23:14
Glad it works. Enjoy

**Closed as completed** 2017-11-29 23:14 UTC

**Comment by haxxus** [comment] 2017-11-29 23:15
by the way , I have not seen this feature on any bot out there , but would it be possible to include a get Discord role Users , so from irc we use such command and we see a list of online users from a certain role name , I guess another command would be useful to display role names .

**Comment by haxxus** [comment] 2017-11-29 23:16
and from discord a command to get users from irc channel , so a list displays online users from irc channel

**Comment by Hackndo** [comment] 2017-11-29 23:18
From IRC point of view, if you use Hexchat, a friend of mine developped a script that works with my discord-irc-sync https://github.com/Shlygly/External-Bridge-Adaptor
Among many features, it adds Discord users to IRC "online users" list.

I'll keep in mind your feature request though, and I'll try to include it when I have some time. Please feel free to add it yourself and create a pull request if you feel like doing it ;)

**Comment by haxxus** [comment] 2017-11-29 23:21
aha , I wish but no I'm not a coder at all :( just some good food for thought , ill be using your bot from now on !

**Comment by haxxus** [comment] 2017-11-29 23:35
question is there multi channel support ? for example if I use different values under:

{
"irc2"
...
}
{
"discord2"
...
}

**Comment by Hackndo** [comment] 2017-11-30 08:39
Not for now
